name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 1 * *' # monthly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.4
    - name: Install Nix ❄️
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Setup Nix Shell
      run: nix-shell --command 'echo All Nix Dependencies have been installed'
    - name: Build WASM package
      run: |
        nix-shell --command '
          cd svd-image-compression-worker
          wasm-pack build
        '
    - name: Install NPM Dependencies
      run: nix-shell --command 'npm ci'
    - name: Webpack build
      run: nix-shell --command 'npm run build'
    - name: ESLint Check
      run: nix-shell --command 'npm run lint:check'
      continue-on-error: true
    - name: Prettier Formatting Check
      run: nix-shell --command 'npm run prettier:check'
      continue-on-error: true
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.2
      if: ${{ github.event_name == 'push' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
